FROM python:3.7

WORKDIR /app

# Copy the requirements.txt and python_env.yaml files and install the required packages
COPY requirements.txt .
RUN pip3 install -r requirements.txt

# Copy the trained XGBoost model into the container
COPY model.xgb .
COPY predict.py .

# Specify the command to run when the container starts
CMD ["python", "-u" "predict.py"]
